### ISSUE TITLE
Disabling all plugins on crash

### ISSUE THREAD

**Issue by creator3** [gyurix/SpigotLib#2]
[TPSMeter#L89](https://github.com/gyurix/SpigotLib/blob/743b959ec9bb2ad3699486125abac74af894b4cd/src/main/java/gyurix/spigotutils/TPSMeter.java#L89)

This disabled all the plugins, and then the server kept running with all the plugins spamming errors into console.

**Comment by zozidalom** [comment]
This function is used to prevent data loss of other plugins by disabling them on crash.

**Comment by creator3** [comment]
How is this different from Spigot's crash detection?

Anyways, the big issue is the server kept running in a broken state. Is there a reason it doesn't trigger a regular shutdown?

**Comment by zozidalom** [comment]
If you can provide me with a crash report then I can tell you more details about your crash, however,
there might be several reasons why Spigot did not trigger the regular shutdown but that has nothing to do with SpigotLib. Probably one of your other plugins crashed the server.

**Comment by creator3** [comment]
SpigotLib seems to be relying on the assumption the regular crash detection will shut the server down immediately after it disables plugins. That's clearly not a good assumption.

The actual crash is from 2 months ago and not the reason I made this issue.

**Comment by gyurix** [comment]
@creator3 
I will make disabling all the plugins on crash detection configurable for resolving this issue, ok?

**Comment by creator3** [comment]
I already disabled the feature myself. I just wanted to save other people from having to troubleshoot why all their plugins were broken and flooding the console with strange errors.

I see 3 possible solutions:

1. Use PluginManager.disablePlugin instead of directly calling onDisable. This way, the plugins won't be receiving events even though they've cleared a bunch of important fields onDisable. On the downside, the plugins would still be offline, including potentially important ones like protection plugins and IPWhitelist.

2. Perform a complete shutdown

3. Remove the feature

**Comment by gyurix** [comment]
Fixed by https://github.com/gyurix/SpigotLib/commit/4cd5e6452d8c056409b31ba52ca1ed742b0799c4
