### ISSUE TITLE
Add Kotlin Support

### ISSUE THREAD

**Issue by NyCodeGHG** [gyurix/SpigotLib#6]
I would find it nice if I could use Kotlin DSLs for things like the gui api. So i can do Something Like this:
```kotlin
player.openGui {
    slots = 27
    title = "Example"
    closable = false
    onClose { ... }
    onOpen { ... }
    item {
         slot = 7
         name = "Example Item"
         clickable = false
         material = Material.APPLE
         onClick(player){
                player.sendMessage("Apple")
         }
         enchantment {
                lvl = 1
                type = Enchantment.UNBREAKING
         }
    }
}
```
As a general rule Kotlin Extensions for the APIs. This would be great.

**Comment by gyurix** [comment]
I don't plan to add support for Kotlin any time soon, however feel free to do any changes related to this in your forked version, whenever you want.
