### ISSUE TITLE
TPS Task and Performance

### ISSUE THREAD

**Issue by A248** [gyurix/SpigotLib#9]
From what I can tell SpigotLIB runs a task every tick to calculate TPS manually. This is not a very optimal feature. If every plugin did this it would be a considerable performance hit.

More importantly, the TPS meter causes another problem. When other plugins are already lagging the server, the scheduler must attempt to keep up. One of the scheduler's biggest tasks, when I tested this out on my server, is simply rescheduling the TPS meter.
https://timings.aikar.co/?id=b5b14419334a4b91a862ac48b2e1e61f

I understand the TPS meter can be disabled. However, it could be greatly optimised. It is a worthwhile feature but could use some improvement.

On Spigot, it is possible to get the TPS via reflection. Also, by caching fields and methods the cost of reflection is reduced.
On Paper, retrieving the TPS is built into the API.

**Comment by gyurix** [comment]
A248, your timings report literally disproves your whole point. You can clearly see from it that the TPS meter has no impact to the servers performance.
What is actually having an impact is a lambda expression used in the SU class, which is probably invoked by other plugins.

You should consider installing the [Spark](https://www.spigotmc.org/resources/spark.57242) plugin to your server to monitor the actual cause of the lag more precisely.

**Comment by A248** [comment]
Sorry, I have since discovered what was causing this lag. Apologies for not remembering to come back to this issue.
